// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRestaurante.Sis.DataAccess.Data;

#nullable disable

namespace SistemaRestaurante.Sis.DataAccess.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20240119212351_AdicionandoTableCardapio")]
    partial class AdicionandoTableCardapio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Sis.Models.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cardapio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Um prato teste, para testar o modelo",
                            Name = "Prato teste",
                            Price = 24.899999999999999,
                            Size = 4
                        });
                });

            modelBuilder.Entity("Sis.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "teste",
                            Value = 200.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
